[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "dagster_pypi"

[tool.ruff]
# Extend root configuration.
extend = "../pyproject.toml"
# Use extend-ignore so that we ignore all the same codes ignored in root.
extend-ignore = [
  # (print found): Allow prints for demo purposes.
  "T201",
]

src = ["dagster_pypi"]
